"""
TrustTunnel — Credentials Sync

Regenerates TrustTunnel credentials file from active keys in the database.
Called after every key mutation (create, delete, toggle, regen).
"""
import logging
import os
import subprocess

from database import KeyDatabase

log = logging.getLogger("trusttunnel-sync")


def sync_tt_credentials(db: KeyDatabase, credentials_path: str):
    """Rewrite TrustTunnel credentials.toml from active keys in DB."""
    keys = db.list_active_keys()

    lines = ["# Auto-generated by Hysteria bot — do not edit manually\n"]
    for k in keys:
        lines.append("[[client]]")
        lines.append(f'username = "{k["key"]}"')
        lines.append(f'password = "{k["key"]}"')
        lines.append("")

    os.makedirs(os.path.dirname(credentials_path), exist_ok=True)
    with open(credentials_path, "w") as f:
        f.write("\n".join(lines))

    try:
        os.chmod(credentials_path, 0o600)
    except OSError:
        pass

    log.info("TrustTunnel credentials synced: %d active keys", len(keys))


def reload_tt_service(service_name: str = "trusttunnel"):
    """Send SIGHUP to TrustTunnel to reload credentials without downtime."""
    try:
        subprocess.run(
            ["systemctl", "reload-or-restart", service_name],
            timeout=10,
            capture_output=True,
        )
        log.info("TrustTunnel service reloaded")
    except Exception as e:
        log.warning("Failed to reload TrustTunnel: %s", e)
